eco/eco/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lookup.urls')),
    path('', include('blog.urls')),
    path('', include('accounts.urls')),
] 

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

eco/lookup/urls.py
from django.urls import path, include
from . import views

app_name ="eco"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:id>/', views.shopdetails, name="shopdetails"),
    path('shopgrid', views.shopgrid, name="shopgrid"),
    path('shopingcart', views.shopingcart, name="shopingcart"),
    path('checkout', views.checkout, name="checkout"),
    path('contact', views.contact, name="contact"),
    path('base', views.base, name ="base"),
]

eco/lookup/models.py
from django.db import models
from datetime import datetime  
from django.utils import timezone
from django.contrib.auth.models import User

class siteInfo(models.Model):
    siteName = models.CharField(max_length=200)
    siteLogo = models.ImageField(upload_to='logo')
    Address = models.CharField(max_length=500)
    helpLine = models.CharField(max_length=200)
    email = models.CharField(max_length=100, default = None)
    topNotice = models.CharField(max_length=500)
    fbLink = models.CharField(max_length=200)
    twiterLink = models.CharField(max_length=200)
    LinkedinLink = models.CharField(max_length=200)
    supportDay =  models.IntegerField()
    supportHour =  models.IntegerField()
    siteDescription = models.CharField(max_length=500)
    aboutUs = models.CharField(max_length=500)
    privacyPolicy = models.CharField(max_length=800)
    deliveryInfomation = models.CharField(max_length=800)



class banner(models.Model):
    mainBanner =  models.ImageField(upload_to='banner')
    subBanner1 =  models.ImageField(upload_to='banner')
    subBanner2 =  models.ImageField(upload_to='banner')

class product(models.Model):
    id = models.AutoField(primary_key=True)
    productName = models.CharField(max_length=200)
    productImg =  models.ImageField(upload_to='productsImg')
    productImg2 =  models.ImageField(upload_to='productsImg', blank = True)
    productImg3 =  models.ImageField(upload_to='productsImg', blank = True)
    productCategories = models.CharField(max_length=200)
    productcolour = models.CharField(max_length=200)
    productPrice = models.IntegerField()
    productOffer = models.BooleanField(default=False)
    featuredproduct = models.BooleanField(default=False)
    OfferPercent = models.IntegerField()
    productDescription = models.CharField(max_length=500, default = 'fhdj fd')

eco/lookup/views.py
from django.shortcuts import render, get_object_or_404
from . models import banner, product, siteInfo
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage



def base(request):
    info = siteInfo.objects.get(id=1)
    Products = product.objects.all()
    herro = None
    return render(request, 'base.html', {'Products':Products, 'herro':herro, 'info': info})

def index(request):
    info = siteInfo.objects.get(id=1)
    Products = product.objects.all()
    Banner = banner.objects.get(id=1)
    herro = 'hero-normal'
    return render(request, 'index.html' , {'banner':Banner, 'Products':Products, 'herro':herro, 'info': info})

def shopdetails(request, id):
    Products = product.objects.all()
    post = get_object_or_404(product, id = id)
    info = siteInfo.objects.get(id=1)
    herro = 'hero-normal'
    return render(request, 'shop-details.html', {'herro':herro, 'post':post, 'Products':Products, 'info': info})

def shopgrid(request):
    info = siteInfo.objects.get(id=1)

    Products = product.objects.all()
    paginator = Paginator(Products, 6)
    
    page = request.GET.get('page')
    
    try:
        Product = paginator.get_page(page)
    except PageNotAnInteger:
        Product = paginator.get_page(1)
    except EmptyPage:
        Product = paginator.get_page(paginator.num_pages)

    herro = 'hero-normal'
    return render(request, 'shop-grid.html', {'page': page,'Products':Product, 'herro':herro, 'info': info})

def shopingcart(request):
    info = siteInfo.objects.get(id=1)
    Products = product.objects.all()
    herro = 'hero-normal'
    return render(request, 'shoping-cart.html', {'Products':Products,'herro':herro, 'info': info})

def checkout(request):
    info = siteInfo.objects.get(id=1)
    Products = product.objects.all()
    herro = 'hero-normal'
    return render(request, 'checkout.html', {'Products':Products,'herro':herro, 'info': info})

def contact(request):
    info = siteInfo.objects.get(id=1)
    Products = product.objects.all()
    herro = 'hero-normal'
    return render(request, 'contact.html', {'Products':Products,'herro':herro, 'info': info})

eco/lookup/templates/checkout.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg="{% static 'img/breadcrumb.jpg'%}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Checkout</h2>
                    <div class="breadcrumb__option">
                        <a href="{% url 'eco:index' %}">Home</a>
                        <span>Checkout</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Checkout Section Begin -->
<section class="checkout spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h6><span class="icon_tag_alt"></span> Have a coupon? <a href="#">Click here</a> to enter your code
                </h6>
            </div>
        </div>
        <div class="checkout__form">
            <h4>Billing Details</h4>
            <form action="#">
                <div class="row">
                    <div class="col-lg-8 col-md-6">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>Fist Name<span>*</span></p>
                                    <input type="text">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>Last Name<span>*</span></p>
                                    <input type="text">
                                </div>
                            </div>
                        </div>
                        <div class="checkout__input">
                            <p>Country<span>*</span></p>
                            <input type="text">
                        </div>
                        <div class="checkout__input">
                            <p>Address<span>*</span></p>
                            <input type="text" placeholder="Street Address" class="checkout__input__add">
                            <input type="text" placeholder="Apartment, suite, unite ect (optinal)">
                        </div>
                        <div class="checkout__input">
                            <p>Town/City<span>*</span></p>
                            <input type="text">
                        </div>
                        <div class="checkout__input">
                            <p>Country/State<span>*</span></p>
                            <input type="text">
                        </div>
                        <div class="checkout__input">
                            <p>Postcode / ZIP<span>*</span></p>
                            <input type="text">
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>Phone<span>*</span></p>
                                    <input type="text">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>Email<span>*</span></p>
                                    <input type="text">
                                </div>
                            </div>
                        </div>
                        <div class="checkout__input__checkbox">
                            <label for="acc">
                                Create an account?
                                <input type="checkbox" id="acc">
                                <span class="checkmark"></span>
                            </label>
                        </div>
                        <p>Create an account by entering the information below. If you are a returning customer
                            please login at the top of the page</p>
                        <div class="checkout__input">
                            <p>Account Password<span>*</span></p>
                            <input type="text">
                        </div>
                        <div class="checkout__input__checkbox">
                            <label for="diff-acc">
                                Ship to a different address?
                                <input type="checkbox" id="diff-acc">
                                <span class="checkmark"></span>
                            </label>
                        </div>
                        <div class="checkout__input">
                            <p>Order notes<span>*</span></p>
                            <input type="text" placeholder="Notes about your order, e.g. special notes for delivery.">
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="checkout__order">
                            <h4>Your Order</h4>
                            <div class="checkout__order__products">Products <span>Total</span></div>
                            <ul>
                                <li>Vegetable’s Package <span>$75.99</span></li>
                                <li>Fresh Vegetable <span>$151.99</span></li>
                                <li>Organic Bananas <span>$53.99</span></li>
                            </ul>
                            <div class="checkout__order__subtotal">Subtotal <span>$750.99</span></div>
                            <div class="checkout__order__total">Total <span>$750.99</span></div>
                            <div class="checkout__input__checkbox">
                                <label for="acc-or">
                                    Create an account?
                                    <input type="checkbox" id="acc-or">
                                    <span class="checkmark"></span>
                                </label>
                            </div>
                            <p>Lorem ipsum dolor sit amet, consectetur adip elit, sed do eiusmod tempor incididunt
                                ut labore et dolore magna aliqua.</p>
                            <div class="checkout__input__checkbox">
                                <label for="payment">
                                    Check Payment
                                    <input type="checkbox" id="payment">
                                    <span class="checkmark"></span>
                                </label>
                            </div>
                            <div class="checkout__input__checkbox">
                                <label for="paypal">
                                    Paypal
                                    <input type="checkbox" id="paypal">
                                    <span class="checkmark"></span>
                                </label>
                            </div>
                            <button type="submit" class="site-btn">PLACE ORDER</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
<!-- Checkout Section End -->
{% endblock %}

eco/lookup/templates/contact.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg="{% static 'img/breadcrumb.jpg'%}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Contact Us</h2>
                    <div class="breadcrumb__option">
                        <a href="{% url 'eco:index' %}">Home</a>
                        <span>Contact Us</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Contact Section Begin -->
<section class="contact spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-3 col-sm-6 text-center">
                <div class="contact__widget">
                    <span class="icon_phone"></span>
                    <h4>Phone</h4>
                    <p>{{info.helpLine}}</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-3 col-sm-6 text-center">
                <div class="contact__widget">
                    <span class="icon_pin_alt"></span>
                    <h4>Address</h4>
                    <p>{{info.Address}}</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-3 col-sm-6 text-center">
                <div class="contact__widget">
                    <span class="icon_mail_alt"></span>
                    <h4>Email</h4>
                    <p>{{info.email}}</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Contact Section End -->

<!-- Map Begin -->
<div class="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d233668.38703692693!2d90.27923991057244!3d23.780573258035957!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755b8b087026b81%3A0x8fa563bbdd5904c2!2sDhaka!5e0!3m2!1sen!2sbd!4v1592672063436!5m2!1sen!2sbd" 
     height="500" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
     
    <div class="map-inside">
        <i class="icon_pin"></i>
        <div class="inside-widget">
            <h4>Address</h4>
            <ul>
                <li>Phone: {{info.helpLine}}</li>
                <li>{{info.Address}}</li>
            </ul>
        </div>
    </div>
</div>
<!-- Map End -->

<!-- Contact Form Begin -->
<div class="contact-form spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="contact__form__title">
                    <h2>Leave Message</h2>
                </div>
            </div>
        </div>
        <form action="#">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <input type="text" placeholder="Your name">
                </div>
                <div class="col-lg-6 col-md-6">
                    <input type="text" placeholder="Your Email">
                </div>
                <div class="col-lg-12 text-center">
                    <textarea placeholder="Your message"></textarea>
                    <button type="submit" class="site-btn">SEND MESSAGE</button>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- Contact Form End -->
{% endblock %}

eco/lookup/templates/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>

eco/lookup/templates/shop-grid.html
{% extends 'base.html' %}
{% block content %}
{% load static %}


<!-- Breadcrumb Section Begin -->
<section class="breadcrumb-section set-bg" data-setbg="{% static 'img/breadcrumb.jpg'%}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Organi Shop</h2>
                    <div class="breadcrumb__option">
                        <a href="{% url 'eco:index'%}">Home</a>
                        <span>Shop</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->

<!-- Product Section Begin -->
<section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-5">
                <div class="sidebar">
                    <div class="sidebar__item">
                        <h4>Department</h4>
                        <ul>
                            {% for porduct in Products %}
                            <li><a href="#">{{porduct.productCategories}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="sidebar__item">
                        <h4>Price</h4>
                        <div class="price-range-wrap">
                            <div class="price-range ui-slider ui-corner-all ui-slider-horizontal ui-widget ui-widget-content"
                                data-min="10" data-max="540">
                                <div class="ui-slider-range ui-corner-all ui-widget-header"></div>
                                <span tabindex="0" class="ui-slider-handle ui-corner-all ui-state-default"></span>
                                <span tabindex="0" class="ui-slider-handle ui-corner-all ui-state-default"></span>
                            </div>
                            <div class="range-slider">
                                <div class="price-input">
                                    <input type="text" id="minamount">
                                    <input type="text" id="maxamount">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sidebar__item sidebar__item__color--option">
                        <h4>Colors</h4>
                        <div class="sidebar__item__color sidebar__item__color--white">
                            <label for="white">
                                White
                                <input type="radio" id="white">
                            </label>
                        </div>
                        <div class="sidebar__item__color sidebar__item__color--gray">
                            <label for="gray">
                                Gray
                                <input type="radio" id="gray">
                            </label>
                        </div>
                        <div class="sidebar__item__color sidebar__item__color--red">
                            <label for="red">
                                Red
                                <input type="radio" id="red">
                            </label>
                        </div>
                        <div class="sidebar__item__color sidebar__item__color--black">
                            <label for="black">
                                Black
                                <input type="radio" id="black">
                            </label>
                        </div>
                        <div class="sidebar__item__color sidebar__item__color--blue">
                            <label for="blue">
                                Blue
                                <input type="radio" id="blue">
                            </label>
                        </div>
                        <div class="sidebar__item__color sidebar__item__color--green">
                            <label for="green">
                                Green
                                <input type="radio" id="green">
                            </label>
                        </div>
                    </div>
                    <div class="sidebar__item">
                        <div class="latest-product__text">
                            <h4>Latest Products</h4>
                            <div class="latest-product__slider owl-carousel">
                                <div class="latest-prdouct__slider__item">
                                    <a href="#" class="latest-product__item">
                                        <div class="latest-product__item__pic">
                                            <img src="{% static 'img/latest-product/lp-1.jpg'%}" alt="">
                                        </div>
                                        <div class="latest-product__item__text">
                                            <h6>Crab Pool Security</h6>
                                            <span>$30.00</span>
                                        </div>
                                    </a>
                                    <a href="#" class="latest-product__item">
                                        <div class="latest-product__item__pic">
                                            <img src="{% static 'img/latest-product/lp-2.jpg'%}" alt="">
                                        </div>
                                        <div class="latest-product__item__text">
                                            <h6>Crab Pool Security</h6>
                                            <span>$30.00</span>
                                        </div>
                                    </a>
                                    <a href="#" class="latest-product__item">
                                        <div class="latest-product__item__pic">
                                            <img src="{% static 'img/latest-product/lp-3.jpg'%}" alt="">
                                        </div>
                                        <div class="latest-product__item__text">
                                            <h6>Crab Pool Security</h6>
                                            <span>$30.00</span>
                                        </div>
                                    </a>
                                </div>
                                <div class="latest-prdouct__slider__item">
                                    <a href="#" class="latest-product__item">
                                        <div class="latest-product__item__pic">
                                            <img src="{% static 'img/latest-product/lp-1.jpg'%}" alt="">
                                        </div>
                                        <div class="latest-product__item__text">
                                            <h6>Crab Pool Security</h6>
                                            <span>$30.00</span>
                                        </div>
                                    </a>
                                    <a href="#" class="latest-product__item">
                                        <div class="latest-product__item__pic">
                                            <img src="{% static 'img/latest-product/lp-2.jpg'%}" alt="">
                                        </div>
                                        <div class="latest-product__item__text">
                                            <h6>Crab Pool Security</h6>
                                            <span>$30.00</span>
                                        </div>
                                    </a>
                                    <a href="#" class="latest-product__item">
                                        <div class="latest-product__item__pic">
                                            <img src="{% static 'img/latest-product/lp-3.jpg'%}" alt="">
                                        </div>
                                        <div class="latest-product__item__text">
                                            <h6>Crab Pool Security</h6>
                                            <span>$30.00</span>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-7">
                <div class="product__discount">
                    <div class="section-title product__discount__title">
                        <h2>Sale Off</h2>
                    </div>
                    <div class="row">
                        <div class="product__discount__slider owl-carousel">

                            {% for porduct in Products %}
                            {% if porduct.productOffer   %}

                            <div class="col-lg-4">
                                <div class="product__discount__item">
                                    <div class="product__discount__item__pic set-bg"
                                        data-setbg="{{ porduct.productImg.url }}">
                                        <div class="product__discount__percent">-{{porduct.OfferPercent}}%</div>
                                        <ul class="product__item__pic__hover">
                                            <li><a href="#"><i class="fa fa-heart"></i></a></li>
                                            <li><a href="{% url 'eco:shopdetails' porduct.id %}"><i class="fa fa-retweet"></i></a></li>
                                            <li><a href="#"><i class="fa fa-shopping-cart"></i></a></li>
                                        </ul>
                                    </div>
                                    <div class="product__discount__item__text">
                                        <span>{{porduct.productCategories}}</span>
                                        <h5><a href="#">{{porduct.productName}}</a></h5>
                                        <div class="product__item__price">

                                            ${{porduct.productPrice}}<span>$ {{ porduct.productOffer }}</span></div>
                                    </div>
                                </div>
                            </div>

                            {% endif %}
                            {% endfor %}

                        </div>
                    </div>
                </div>
                <div class="filter__item">
                    <div class="row">
                        <div class="col-lg-4 col-md-5">
                            <div class="filter__sort">
                                <span>Sort By</span>
                                <select>
                                    <option value="0">Default</option>
                                    <option value="0">Default</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <div class="filter__found">
                                <h6><span>16</span> Products found</h6>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-3">
                            <div class="filter__option">
                                <span class="icon_grid-2x2"></span>
                                <span class="icon_ul"></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    {% for porduct in Products %}
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="product__item">
                            <div class="product__item__pic set-bg" data-setbg="{{ porduct.productImg.url }}">
                                <ul class="product__item__pic__hover">
                                    <li><a href="#"><i class="fa fa-heart"></i></a></li>
                                    <li><a href="{% url 'eco:shopdetails' porduct.id %}"><i class="fa fa-retweet"></i></a></li>
                                    <li><a href="#"><i class="fa fa-shopping-cart"></i></a></li>
                                </ul>
                            </div>
                            <div class="product__item__text">
                                <h6><a href="#">{{porduct.productName}}</a></h6>
                                <h5>{{porduct.productPrice}} tk.</h5>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                 
                <div class="product__pagination">
                    {% if Products.has_previous %}
                    <a href="?page={{ Products.previous_page_number }}"><i class="fa fa-long-arrow-left"></i></a>
                    {% endif %}
                    <span class="current">
                        <a href="">{{ Products.number }} </a> 
                    </span>
            
                    {% if Products.has_next %}
                        <a href="?page={{ Products.next_page_number }}"><i class="fa fa-long-arrow-right"></i></a>
                    {% endif %}
                </div>
                 
            </div>
        </div>
    </div>
</section>
<!-- Product Section End -->
{% endblock %}